In [6]:
import numpy as np
import pandas as pd

In [13]:
# create a DataFrame from the oil file, drop missing values
oil = pd.read_csv("./oil.csv").dropna()
#  pd.to_csv

# Grab 100 rows of oil prices
oil_array = np.array(oil["dcoilwtico"].iloc[1000:1100])

oil_array

array([52.22, 51.44, 51.98, 52.01, 52.82, 54.01, 53.8 , 53.75, 52.36,
       53.26, 53.77, 53.98, 51.95, 50.82, 52.19, 53.01, 52.36, 52.45,
       51.12, 51.39, 52.33, 52.77, 52.38, 52.14, 53.24, 53.18, 52.63,
       52.75, 53.9 , 53.55, 53.81, 53.01, 52.19, 52.37, 52.99, 53.84,
       52.96, 53.21, 53.11, 53.41, 53.41, 54.02, 53.61, 54.48, 53.99,
       54.04, 54.  , 53.82, 52.63, 53.33, 53.19, 52.68, 49.83, 48.75,
       48.05, 47.95, 47.24, 48.34, 48.3 , 48.34, 47.79, 47.02, 47.29,
       47.  , 47.3 , 47.02, 48.36, 49.47, 50.3 , 50.54, 50.25, 50.99,
       51.14, 51.69, 52.25, 53.06, 53.38, 53.12, 53.19, 52.62, 52.46,
       50.49, 50.26, 49.64, 48.9 , 49.22, 49.22, 48.96, 49.31, 48.83,
       47.65, 47.79, 45.55, 46.23, 46.46, 45.84, 47.28, 47.81, 47.83,
       48.86])

NEW

In [19]:
items = ["coffee", "bananas", "tea", "coconut", "sugar"]
sales_items = sales_series[:5]
sales_items

NameError: name 'sales_series' is not defined

In [20]:
# create a DataFrame from the oil file, drop missing values
oil = pd.read_csv("./oil.csv").dropna()
oil

date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

In [24]:
oil["date"]

1       2013-01-02
2       2013-01-03
3       2013-01-04
4       2013-01-07
5       2013-01-08
           ...    
1213    2017-08-25
1214    2017-08-28
1215    2017-08-29
1216    2017-08-30
1217    2017-08-31
Name: date, Length: 1175, dtype: object

In [26]:
dates = pd.Series(oil["date"]).iloc[1000:1100]
dates

1035    2016-12-20
1036    2016-12-21
1037    2016-12-22
1038    2016-12-23
1040    2016-12-27
           ...    
1135    2017-05-09
1136    2017-05-10
1137    2017-05-11
1138    2017-05-12
1139    2017-05-15
Name: date, Length: 100, dtype: object

In [27]:
oil_series.index = dates
oil_series

NameError: name 'oil_series' is not defined

In [42]:
sales = [0, 5, 155, 0, 518, 9, 1827, 616,317, 325]
sales_series = pd.Series(sales, name="Sales")
sales_series = sales_series[:5]
sales_series

0      0
1      5
2    155
3      0
4    518
Name: Sales, dtype: int64

In [33]:
sales_series.loc[sales_series > 0]b

1      5
2    155
4    518
Name: Sales, dtype: int64

In [34]:
sales_series > 0

0    False
1     True
2     True
3    False
4     True
Name: Sales, dtype: bool

In [43]:
sales_series.index = items
mask = (sales_series > 0) & (sales_series.index == "coffee")
sales_series.loc[mask]

Series([], Name: Sales, dtype: int64)

In [44]:
sales_series == 5

coffee     False
bananas     True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [45]:
sales_series.eq(5)

coffee     False
bananas     True
tea        False
coconut    False
sugar      False
Name: Sales, dtype: bool

In [46]:
sales_series.index.isin(["coffee", "tea"])

array([ True, False,  True, False, False])

In [47]:
~sales_series.index.isin(["coffee", "tea"])

array([False,  True, False,  True,  True])

SORTING

In [50]:
sales_series.sort_values(ascending=True)

coffee       0
coconut      0
bananas      5
tea        155
sugar      518
Name: Sales, dtype: int64

In [51]:
sales_series.sort_index(ascending=True)

bananas      5
coconut      0
coffee       0
sugar      518
tea        155
Name: Sales, dtype: int64

# Assignment 3: Sorting and Filtering Series

* First, get the 10 lowest prices from the data. 
* Sort the 10 lowest prices by date, starting with the most recent and ending with the oldest price.

* Finally, use the list of provided dates. Select only rows with these dates that had a price of less than 50 dollars per barrel.

In [68]:
# list of dates to be used to solve bullet 3

dates = [
    "2016-12-22",
    "2017-05-03",
    "2017-01-06",
    "2017-03-05",
    "2017-02-12",
    "2017-03-21",
    "2017-04-14",
    "2017-04-15",
]
dates

['2016-12-22',
 '2017-05-03',
 '2017-01-06',
 '2017-03-05',
 '2017-02-12',
 '2017-03-21',
 '2017-04-14',
 '2017-04-15']

In [54]:
# Assuming you have already read the data and dropped missing values
oil = pd.read_csv("./oil.csv").dropna()
oil

date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

In [59]:
# Step 1: Get the 10 lowest prices
lowest_prices = oil.nsmallest(10, 'dcoilwtico')
lowest_prices

date  dcoilwtico
812  2016-02-11       26.19
796  2016-01-20       26.68
811  2016-02-10       27.54
810  2016-02-09       27.96
795  2016-01-19       28.47
815  2016-02-16       29.05
813  2016-02-12       29.32
793  2016-01-15       29.45
800  2016-01-26       29.54
797  2016-01-21       29.55

In [60]:
# Step 2: Sort the 10 lowest prices by date
lowest_prices_sorted = lowest_prices.sort_values(by='date', ascending=False)
lowest_prices_sorted

date  dcoilwtico
815  2016-02-16       29.05
813  2016-02-12       29.32
812  2016-02-11       26.19
811  2016-02-10       27.54
810  2016-02-09       27.96
800  2016-01-26       29.54
797  2016-01-21       29.55
796  2016-01-20       26.68
795  2016-01-19       28.47
793  2016-01-15       29.45

In [73]:
# Step 3: Use the list of provided dates and filter rows with prices less than 50 dollars per barrel
filtered_prices = oil[(oil['date'].isin(provided_dates)) & (oil['dcoilwtico'] < 50)]
filtered_prices

date  dcoilwtico
1091  2017-03-08       49.83
1092  2017-03-09       48.75
1093  2017-03-10       48.05
1094  2017-03-13       47.95
1095  2017-03-14       47.24
1096  2017-03-15       48.34
1097  2017-03-16       48.30
1098  2017-03-17       48.34
1099  2017-03-20       47.79
1100  2017-03-21       47.02
1101  2017-03-22       47.29
1102  2017-03-23       47.00
1103  2017-03-24       47.30
1104  2017-03-27       47.02
1105  2017-03-28       48.36
1106  2017-03-29       49.47
1123  2017-04-21       49.64
1124  2017-04-24       48.90
1125  2017-04-25       49.22
1126  2017-04-26       49.22
1127  2017-04-27       48.96
1128  2017-04-28       49.31
1129  2017-05-01       48.83
1130  2017-05-02       47.65
1131  2017-05-03       47.79
1132  2017-05-04       45.55
1133  2017-05-05       46.23
1134  2017-05-08       46.46
1135  2017-05-09       45.84
1136  2017-05-10       47.28
1137  2017-05-11       47.81
1138  2017-05-12       47.83
1139  2017-05-15       48.86

In [76]:
sales_series

coffee       0
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: int64

In [81]:
dollar_sales_series = "5"
sales_series = sales_series.astype("string")
sales_series

coffee       0
bananas      5
tea        155
coconut      0
sugar      518
Name: Sales, dtype: string

In [82]:
dollar_sales_series

'5'

In [85]:
dollar_sales_series = "$" + sales_series.astype("string")
dollar_sales_series

coffee       $0
bananas      $5
tea        $155
coconut      $0
sugar      $518
Name: Sales, dtype: string

In [86]:
dollar_sales_series.str.count("0") #. astype("fLoat")

coffee     1
bananas    0
tea        0
coconut    1
sugar      0
Name: Sales, dtype: Int64

### Assignment 4: Series Operations

* Increase the prices in the oil series by 10%, and add an additional 2 dollars per barrel on top of that.

* Then, create a series that represents the difference between each price and max price.

* Finally, extract the month from the string dates in the index and store them as an integer in their own series.

### Задание 4: Серийные операции

* Увеличьте цены в серии цен на нефть на 10 % и добавьте к ним еще 2 доллара за баррель.

* Затем создайте серию, представляющую разницу между каждой ценой и максимальной ценой.

* Наконец, извлеките месяц из строковых дат в индексе и сохраните их как целое число в их собственной серии.

In [97]:
oil = pd.read_csv("./oil.csv").dropna()
oil

date  dcoilwtico
1     2013-01-02       93.14
2     2013-01-03       92.97
3     2013-01-04       93.12
4     2013-01-07       93.20
5     2013-01-08       93.21
...          ...         ...
1213  2017-08-25       47.65
1214  2017-08-28       46.40
1215  2017-08-29       46.46
1216  2017-08-30       45.96
1217  2017-08-31       47.26

[1175 rows x 2 columns]

In [98]:
oil['dcoilwtico'] = oil['dcoilwtico'] * 1.10 + 2
oil

date  dcoilwtico
1     2013-01-02     104.454
2     2013-01-03     104.267
3     2013-01-04     104.432
4     2013-01-07     104.520
5     2013-01-08     104.531
...          ...         ...
1213  2017-08-25      54.415
1214  2017-08-28      53.040
1215  2017-08-29      53.106
1216  2017-08-30      52.556
1217  2017-08-31      53.986

[1175 rows x 2 columns]

In [102]:
oil

date  dcoilwtico
1     2013-01-02     104.454
2     2013-01-03     104.267
3     2013-01-04     104.432
4     2013-01-07     104.520
5     2013-01-08     104.531
...          ...         ...
1213  2017-08-25      54.415
1214  2017-08-28      53.040
1215  2017-08-29      53.106
1216  2017-08-30      52.556
1217  2017-08-31      53.986

[1175 rows x 2 columns]

# Assignment 6: Missing Data
There were some erroneous prices in our data, so they were filled in with missing values.
Can you confirm the number of missing values in the price column?
Once you've done that, fill the prices in with the median of the oil price series.

In [114]:
oil = pd.read_csv("./oil.csv", parse_dates=['date'], index_col='date').dropna()
oil_series = oil['dcoilwtico']
oil_series

date
2013-01-02    93.14
2013-01-03    92.97
2013-01-04    93.12
2013-01-07    93.20
2013-01-08    93.21
              ...  
2017-08-25    47.65
2017-08-28    46.40
2017-08-29    46.46
2017-08-30    45.96
2017-08-31    47.26
Name: dcoilwtico, Length: 1175, dtype: float64

In [115]:
oil['correct_column_name'].fillna(oil['correct_column_name'].median(), inplace=True)

KeyError: 'correct_column_name'