In [5]:
import numpy as np

In [9]:
sales = [0, 5, 155, 0, 518, 9, 1827, 616, 317, 325]
sales_array = np.array(sales)

In [10]:
sales_array


array([   0,    5,  155,    0,  518,    9, 1827,  616,  317,  325])

### ndim - dimenstion (axes) in the array
### shape - the size of the array in each dimention
### size - the total number
### dtype - the data type

In [13]:
print(f"ndim: {sales_array.ndim}")

ndim: 1


In [15]:
print(f"shape: {sales_array.shape}")

shape: (10,)


In [16]:
print(f"size: {sales_array.size}")

size: 10


In [18]:
print(f"dtype: {sales_array.dtype}")

dtype: int64


In [25]:
sales = [[0, 5, 155, 0, 518], [9, 1827, 616, 317, 325]]
sales_array = np.array(sales)

In [26]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [27]:
print(f"shape: {sales_array.shape}")

shape: (2, 5)


In [28]:
print(f"size: {sales_array.size}")

size: 10


In [29]:
print(f"dtype: {sales_array.dtype}")

dtype: int64



# Assignment 1: Array Basics

Can you import Numpy and convert the following list into an array?

Once you've done that report the following about the array:
• The number of dimensions

• The shape

• The number of elements in the array

• The type of data contained inside

In [30]:
my_list = [x * 10 for x in range(1,11)]
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [31]:
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [33]:
my_array.ndim

1

In [34]:
my_array.shape

(10,)

In [35]:
my_array.size

10

In [36]:
my_array.dtype

dtype('int64')

In [39]:
my_two_dim_array = my_array.reshape(5,2)
my_two_dim_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [40]:
np.ones((2,3),)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
ones.dtype

dtype('float64')

In [48]:
zeros = np.zeros((5, 5), dtype=int)
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:
myrange = np.arange(10)
myrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
my_linspace = np.linspace(0,100, 5)
my_linspace

array([  0.,  25.,  50.,  75., 100.])

In [53]:
np.arange(1,9,2).reshape(2,2)

array([[1, 3],
       [5, 7]])

## np.default_rng(seed) 
## default_rng.random(n)
## default_rng.normal (mean, stdev, n)

In [57]:
rng = np.random.default_rng(123456)
random_array = rng.random(10)
random_array

array([0.63651375, 0.38481166, 0.04744542, 0.95525274, 0.90605094,
       0.45696955, 0.28053348, 0.6361488 , 0.98071069, 0.81243179])

In [60]:
random_normal = rng.normal(5, 1, 10)
random_normal

array([4.83863835, 5.13035288, 3.69978611, 4.0935658 , 3.23428591,
       4.86469245, 5.08626036, 5.6060993 , 6.22908319, 6.57168118])

### • Create the same array from assignment 1 using a NumPy function.
### • Make it 5 rows and 2 columns.
### • It's ok if the datatype is float or int.


In [68]:
my_array = np.arange(10,101, 10).reshape(5, 2)
my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [70]:

my_linspace

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [72]:
my_fun_array = (np.arange(1,11)*10).reshape(5, 2)
my_fun_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

### Can you create a 3x3 array of random numbers between 0 and 1? 
### Use a random seed of 2022.
### Store the random array in a variable called random_array

In [93]:
my_rng = np.random.default_rng(2020)
random_array = my_rng.random(9).reshape(3,3)
random_array

array([[0.46830754, 0.51434223, 0.86398828],
       [0.71938687, 0.33349788, 0.88166362],
       [0.51866486, 0.52321942, 0.7223887 ]])

In [95]:
integer_array = np. arange (12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [209]:
integer_array[4]

4

In [210]:
integer_array[-2]

10

In [98]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [211]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

#### array[row index, column index] - indexing to access a single element (0-indexed)
#### array[start:stop:step size, start:stop:step size] - slicing to access a series of elements

In [101]:
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
new_array[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
new_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
new_array[:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [105]:
new_array[2, 1]

9

• Grab the first two 'rows' of the array
• Grab the entire first column
• Finally, grab the second selement of the third row.

In [106]:
random_array

array([[0.46830754, 0.51434223, 0.86398828],
       [0.71938687, 0.33349788, 0.88166362],
       [0.51866486, 0.52321942, 0.7223887 ]])

In [107]:
random_array[:2, :]

array([[0.46830754, 0.51434223, 0.86398828],
       [0.71938687, 0.33349788, 0.88166362]])

In [109]:
random_array[:, 0]

array([0.46830754, 0.71938687, 0.51866486])

In [111]:
random_array[2, 1]

0.523219417246932

## Arithmetic operators can be used to perform array operations

In [112]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [113]:
sales_array + 2

array([[   2,    7,  157,    2,  520],
       [  11, 1829,  618,  319,  327]])

In [114]:
quantity = sales_array[0, :]
quantity

array([  0,   5, 155,   0, 518])

In [117]:
price = sales_array[1, :]

In [118]:
price

array([   9, 1827,  616,  317,  325])

In [119]:
quantity * price

array([     0,   9135,  95480,      0, 168350])

* prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])
* Before we do that,

*Add a 5 dollar shipping fee to each price. Call this array total.

#### Once we have that, we want to use the random_array created in assignment 2 and apply them to the 6 prices.

* Grab the first 6 numbers from random_array, reshape it to one dimension. Call this discount_pct.
* Subtract discount_pct FROM 1, store this in pct_owed.
* Multiply pct_owed by total to get the final amount owed.

In [126]:
random_array

array([[0.46830754, 0.51434223, 0.86398828],
       [0.71938687, 0.33349788, 0.88166362],
       [0.51866486, 0.52321942, 0.7223887 ]])

In [127]:
prices = np.array([5.99, 6.99, 22.49, 99.99, 4.99, 49.99])

In [128]:
prices

array([ 5.99,  6.99, 22.49, 99.99,  4.99, 49.99])

In [130]:
total = prices + 5
total

array([ 10.99,  11.99,  27.49, 104.99,   9.99,  54.99])

In [137]:
discount_pct = random_array[:2].reshape(6)
discount_pct

array([0.46830754, 0.51434223, 0.86398828, 0.71938687, 0.33349788,
       0.88166362])

In [138]:
pct_owed = 1 - discount_pct
pct_owed

array([0.53169246, 0.48565777, 0.13601172, 0.28061313, 0.66650212,
       0.11833638])

In [139]:
final_owed = total * pct_owed
final_owed.round(2)

array([ 5.84,  5.82,  3.74, 29.46,  6.66,  6.51])

## FILTERING ARRAYS
• You can filter arrays by indexing them with a logical test

In [140]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [141]:
sales_array != 0

array([[False,  True,  True, False,  True],
       [ True,  True,  True,  True,  True]])

In [142]:
sales_array[sales_array !=0]

array([   5,  155,  518,    9, 1827,  616,  317,  325])

In [143]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [144]:
sales_array[(sales_array==616)]

array([616])

In [146]:
sales_array[(sales_array==616) | (sales_array<100)]

array([  0,   5,   0,   9, 616])

In [150]:
sales_array[(sales_array>100) & (sales_array<500)]

array([155, 317, 325])

In [154]:
mask = (sales_array>100) & (sales_array<500)
sales_array[mask]

array([155, 317, 325])

In [155]:
product_array = np. array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'])
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [156]:
sales_array = sales_array[0,:]
sales_array

array([  0,   5, 155,   0, 518])

In [157]:
product_array[sales_array > 0]

array(['vegetables', 'cereal', 'eggs'], dtype='<U10')

### MODIFYING ARRAY VALUES
• You can modify array values by assigning new ones

In [158]:
sales_array

array([  0,   5, 155,   0, 518])

In [160]:
sales_array[1] = 25

In [161]:
sales_array

array([  0,  25, 155,   0, 518])

In [162]:
sales_array[sales_array == 0] = 5
sales_array

array([  5,  25, 155,   5, 518])

### The where function
np.where(logici, value if true, value if false)

In [163]:
product_array

array(['fruits', 'vegetables', 'cereal', 'dairy', 'eggs'], dtype='<U10')

In [166]:
inventory_array = np.array([12, 102, 18, 0, 0])
inventory_array

array([ 12, 102,  18,   0,   0])

In [168]:
np.where(inventory_array<= 0, "Out of Stock", "In Stock")

array(['In Stock', 'In Stock', 'In Stock', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

In [169]:
np.where(inventory_array<= 0, "Out of Stock", product_array)

array(['fruits', 'vegetables', 'cereal', 'Out of Stock', 'Out of Stock'],
      dtype='<U12')

#### ARray aggregation methods

In [175]:
sales = [0, 5, 155, 0, 518, 9, 1827,616, 317, 325]
sales_array = np.array(sales) .reshape(2,5)
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [176]:
sales_array.sum()

3772

In [177]:
sales_array.mean()

377.2

In [178]:
sales_array.max()

1827

In [179]:
sales_array.min()

0

In [180]:
sales_array.sum(axis=0)

array([   9, 1832,  771,  317,  843])

In [182]:
sales_array.sum(axis=1)

array([ 678, 3094])

In [183]:
np.median(sales_array)

236.0

In [184]:
np.percentile(sales_array,90)

737.0999999999996

In [185]:
np.unique(sales_array)

array([   0,    5,    9,  155,  317,  325,  518,  616, 1827])

In [186]:
np.sqrt(sales_array)

array([[ 0.        ,  2.23606798, 12.4498996 ,  0.        , 22.75961335],
       [ 3.        , 42.74342055, 24.81934729, 17.80449381, 18.02775638]])

In [187]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [188]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [190]:
sales_array.sort(axis=0)

In [191]:
sales_array

array([[   0,    5,  155,    0,  325],
       [   9, 1827,  616,  317,  518]])

In [195]:
sales_array.sort(axis=1)
sales_array

array([[   0,    0,    5,  155,  325],
       [   9,  317,  518,  616, 1827]])

In [196]:
def for_loop_multiply_lists(list1, list2):
    product_list = []
    for element1, element2 in zip(list1, list2):
        product_list.append(element1 * element2)
    return product_list

def multiply_arrays(array1, array2):
    return array1 * array2

In [202]:
list1 = list(range(1000))
list2 = list(range(1000))

In [199]:
%%timeit -r 5 -n 10000
for_loop_multiply_lists(list1, list2)

28.4 µs ± 1.11 µs per loop (mean ± std. dev. of 5 runs, 10,000 loops each)


In [207]:
array1 = np.array(list1)
array2 = np.array(list2)

In [208]:
%timeit -r 5 -n 10000 multiply_arrays(array1, array2)

1.09 µs ± 560 ns per loop (mean ± std. dev. of 5 runs, 10,000 loops each)
