In [5]:
import numpy as np

In [9]:
sales = [0, 5, 155, 0, 518, 9, 1827, 616, 317, 325]
sales_array = np.array(sales)

In [10]:
sales_array


array([   0,    5,  155,    0,  518,    9, 1827,  616,  317,  325])

### ndim - dimenstion (axes) in the array
### shape - the size of the array in each dimention
### size - the total number
### dtype - the data type

In [13]:
print(f"ndim: {sales_array.ndim}")

ndim: 1


In [15]:
print(f"shape: {sales_array.shape}")

shape: (10,)


In [16]:
print(f"size: {sales_array.size}")

size: 10


In [18]:
print(f"dtype: {sales_array.dtype}")

dtype: int64


In [25]:
sales = [[0, 5, 155, 0, 518], [9, 1827, 616, 317, 325]]
sales_array = np.array(sales)

In [26]:
sales_array

array([[   0,    5,  155,    0,  518],
       [   9, 1827,  616,  317,  325]])

In [27]:
print(f"shape: {sales_array.shape}")

shape: (2, 5)


In [28]:
print(f"size: {sales_array.size}")

size: 10


In [29]:
print(f"dtype: {sales_array.dtype}")

dtype: int64



# Assignment 1: Array Basics

Can you import Numpy and convert the following list into an array?

Once you've done that report the following about the array:
• The number of dimensions

• The shape

• The number of elements in the array

• The type of data contained inside

In [30]:
my_list = [x * 10 for x in range(1,11)]
my_list

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]

In [31]:
my_array = np.array(my_list)
my_array

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [33]:
my_array.ndim

1

In [34]:
my_array.shape

(10,)

In [35]:
my_array.size

10

In [36]:
my_array.dtype

dtype('int64')

In [39]:
my_two_dim_array = my_array.reshape(5,2)
my_two_dim_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [40]:
np.ones((2,3),)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [45]:
ones = np.ones((10,10))
ones

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [47]:
ones.dtype

dtype('float64')

In [48]:
zeros = np.zeros((5, 5), dtype=int)
zeros

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [49]:
myrange = np.arange(10)
myrange

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
my_linspace = np.linspace(0,100, 5)
my_linspace

array([  0.,  25.,  50.,  75., 100.])

In [53]:
np.arange(1,9,2).reshape(2,2)

array([[1, 3],
       [5, 7]])

## np.default_rng(seed) 
## default_rng.random(n)
## default_rng.normal (mean, stdev, n)

In [57]:
rng = np.random.default_rng(123456)
random_array = rng.random(10)
random_array

array([0.63651375, 0.38481166, 0.04744542, 0.95525274, 0.90605094,
       0.45696955, 0.28053348, 0.6361488 , 0.98071069, 0.81243179])

In [60]:
random_normal = rng.normal(5, 1, 10)
random_normal

array([4.83863835, 5.13035288, 3.69978611, 4.0935658 , 3.23428591,
       4.86469245, 5.08626036, 5.6060993 , 6.22908319, 6.57168118])

### • Create the same array from assignment 1 using a NumPy function.
### • Make it 5 rows and 2 columns.
### • It's ok if the datatype is float or int.


In [68]:
my_array = np.arange(10,101, 10).reshape(5, 2)
my_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

In [70]:
my_linspace = np.linspace(10,100, 10).reshape(5, 2)
my_linspace

array([[ 10.,  20.],
       [ 30.,  40.],
       [ 50.,  60.],
       [ 70.,  80.],
       [ 90., 100.]])

In [72]:
my_fun_array = (np.arange(1,11)*10).reshape(5, 2)
my_fun_array

array([[ 10,  20],
       [ 30,  40],
       [ 50,  60],
       [ 70,  80],
       [ 90, 100]])

### Can you create a 3x3 array of random numbers between 0 and 1? 
### Use a random seed of 2022.
### Store the random array in a variable called random_array

In [93]:
my_rng = np.random.default_rng(2020)
random_array = my_rng.random(9).reshape(3,3)
random_array

array([[0.46830754, 0.51434223, 0.86398828],
       [0.71938687, 0.33349788, 0.88166362],
       [0.51866486, 0.52321942, 0.7223887 ]])

In [95]:
integer_array = np. arange (12)
integer_array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [96]:
integer_array[4]

4

In [97]:
integer_array[-2]

10

In [98]:
integer_array[:5]

array([0, 1, 2, 3, 4])

In [99]:
integer_array[:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [100]:
integer_array[::2]

array([ 0,  2,  4,  6,  8, 10])

#### array[row index, column index] - indexing to access a single element (0-indexed)
#### array[start:stop:step size, start:stop:step size] - slicing to access a series of elements

In [101]:
new_array = integer_array.reshape(3,4)
new_array

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [102]:
new_array[:, :]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
new_array[1:, :]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [104]:
new_array[:, 1:]

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11]])

In [105]:
new_array[2, 1]

9

• Grab the first two 'rows' of the array
• Grab the entire first column
• Finally, grab the second selement of the third row.

In [106]:
random_array

array([[0.46830754, 0.51434223, 0.86398828],
       [0.71938687, 0.33349788, 0.88166362],
       [0.51866486, 0.52321942, 0.7223887 ]])

In [107]:
random_array[:2, :]

array([[0.46830754, 0.51434223, 0.86398828],
       [0.71938687, 0.33349788, 0.88166362]])

In [109]:
random_array[:, 0]

array([0.46830754, 0.71938687, 0.51866486])

In [110]:
random_array[2, 1]

0.523219417246932