In [4]:
import numpy as np

### 1

In [5]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data

array([[44, 33, 52, 22, 36],
       [44, 33, 62, 72, 16],
       [49, 45, 92, 11, 56],
       [81, 82,  1,  3, 48],
       [18, 90, 29, 10, 71]])

In [6]:
data[[1, 3], :] = data[[3, 1], :]
data

array([[44, 33, 52, 22, 36],
       [81, 82,  1,  3, 48],
       [49, 45, 92, 11, 56],
       [44, 33, 62, 72, 16],
       [18, 90, 29, 10, 71]])

### 2

In [7]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data

array([[36, 28, 55, 40, 17],
       [49, 77, 65, 79, 55],
       [ 2, 38, 77, 57, 66],
       [40, 97, 94, 77, 55],
       [42, 33, 52,  8, 41]])

In [9]:
normalized_data = (data - np.min(data)) / (np.max(data) - np.min(data))
normalized_data

array([[0.35789474, 0.27368421, 0.55789474, 0.4       , 0.15789474],
       [0.49473684, 0.78947368, 0.66315789, 0.81052632, 0.55789474],
       [0.        , 0.37894737, 0.78947368, 0.57894737, 0.67368421],
       [0.4       , 1.        , 0.96842105, 0.78947368, 0.55789474],
       [0.42105263, 0.32631579, 0.52631579, 0.06315789, 0.41052632]])

### 3

In [10]:
z_score_data = (data - np.mean(data)) / np.std(data)
z_score_data

array([[-0.63417064, -0.96794466,  0.15854266, -0.46728363, -1.42688394],
       [-0.09178786,  1.07642122,  0.57576019,  1.15986472,  0.15854266],
       [-2.05271023, -0.55072713,  1.07642122,  0.24198616,  0.61748194],
       [-0.46728363,  1.91085627,  1.78569101,  1.07642122,  0.15854266],
       [-0.38384012, -0.7593359 ,  0.0333774 , -1.80237971, -0.42556188]])

### 4

In [16]:
data = np.array(np.random.randint(1, 100, size=25)).reshape(5, 5)
data

array([[44, 86, 66, 45,  9],
       [15,  8,  8, 68, 46],
       [76, 12, 28, 46, 45],
       [16, 22, 59, 41, 80],
       [92, 12, 99, 24, 82]])

In [15]:
vectorized_data = np.ravel(data)
vectorized_data

array([36, 28, 55, 40, 17, 49, 77, 65, 79, 55,  2, 38, 77, 57, 66, 40, 97,
       94, 77, 55, 42, 33, 52,  8, 41])

In [14]:
sub_arrays = np.array_split(vectorized_data, 5)
sub_arrays

[array([36, 28, 55, 40, 17]),
 array([49, 77, 65, 79, 55]),
 array([ 2, 38, 77, 57, 66]),
 array([40, 97, 94, 77, 55]),
 array([42, 33, 52,  8, 41])]

### 5

In [18]:
vector1 = np.array([3, 5, 6, 7, 8])
vector1

array([3, 5, 6, 7, 8])

In [19]:
vector2 = np.array([2, 4, 6, 8, 10])
vector2

array([ 2,  4,  6,  8, 10])

In [21]:
dot_product_result = np.dot(vector1, vector2)
dot_product_result

198

### 6

In [25]:
data1 = np.array(np.random.randint(1, 30, size=9)).reshape(3, 3)
data1

array([[27, 22, 24],
       [ 6, 21,  8],
       [25, 10,  4]])

In [26]:
data2 = np.array(np.random.randint(1, 30, size=9)).reshape(3, 3)
data2

array([[12, 17,  4],
       [14, 10, 25],
       [12, 22,  8]])

In [28]:
result_data = np.dot(data1, data2)
result_data

array([[ 920, 1207,  850],
       [ 462,  488,  613],
       [ 488,  613,  382]])

### 7

In [31]:
identity_matrix = np.eye(3)
identity_matrix 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [32]:
scaled_matrix = 2 * identity_matrix
scaled_matrix

array([[2., 0., 0.],
       [0., 2., 0.],
       [0., 0., 2.]])

In [33]:
inverse_matrix = np.linalg.inv(scaled_matrix)
inverse_matrix

array([[0.5, 0. , 0. ],
       [0. , 0.5, 0. ],
       [0. , 0. , 0.5]])

### 8

In [36]:
data = np.array(np.random.randint(1, 50, size=9)).reshape(3, 3)
data

array([[ 8, 46, 17],
       [13, 27,  6],
       [40, 49, 43]])

In [46]:
matrix_3x3 = data[:3, :3]

In [49]:
eigenvalues, eigenvectors = np.linalg.eig(matrix_3x3)
eigenvalues

array([ 73.10477066, -12.2103332 ,  17.10556253])

In [50]:
eigenvectors

array([[-0.3929237 , -0.87267912, -0.14390946],
       [-0.226767  ,  0.22284868, -0.36798007],
       [-0.89117209,  0.43447627,  0.91862981]])

### 9

In [60]:
data = np.array(np.random.randint(1, 10, size=25), dtype=float).reshape(5, 5)
data

array([[6., 9., 1., 3., 7.],
       [4., 9., 3., 5., 3.],
       [7., 5., 9., 7., 2.],
       [4., 9., 2., 9., 5.],
       [2., 4., 7., 8., 3.]])

In [61]:
np.random.seed(42)
missing_indices = np.random.choice(range(data.size), size=5, replace=False)
data.flat[missing_indices] = np.nan

In [64]:
print(data)

[[nan  9.  1.  3.  7.]
 [ 4.  9.  3. nan  3.]
 [ 7. nan  9.  7.  2.]
 [ 4. nan  2.  9.  5.]
 [ 2.  4.  7. nan  3.]]


In [63]:
print(np.argwhere(np.isnan(data)))

[[0 0]
 [1 3]
 [2 1]
 [3 1]
 [4 3]]


### 10

In [66]:
data_base = np.array([[20., 15., np.nan, 10., np.nan],
                              [30., 25., 18., np.nan, 12.],
                              [np.nan, 22., 28., 14., 16.],
                              [40., np.nan, 36., 24., 28.],
                              [32., 18., 14., np.nan, 20.]])

In [67]:
mean_value = np.nanmean(data_base)

In [70]:
data_base[np.isnan(data_base)] = mean_value
data_base

array([[20.        , 15.        , 22.21052632, 10.        , 22.21052632],
       [30.        , 25.        , 18.        , 22.21052632, 12.        ],
       [22.21052632, 22.        , 28.        , 14.        , 16.        ],
       [40.        , 22.21052632, 36.        , 24.        , 28.        ],
       [32.        , 18.        , 14.        , 22.21052632, 20.        ]])